-- Opportunities with verified URLs, detailed Spanish descriptions, educational metadata
-- Run after 005_add_educational_metadata.sql
-- Schema: type (enum: scholarship, research, internship, course), funding (bool), deadline (required)

DELETE FROM opportunities;

-- SCHOLARSHIPS
INSERT INTO opportunities (title, institution, location, type, funding, description, link, deadline, tags, educational_level, educational_field) VALUES
('Fulbright (México)', 'US Embassy / COMEX', 'Estados Unidos', 'scholarship', true, 'Programa de intercambio educativo del gobierno de Estados Unidos que ofrece becas completas para estudios de posgrado, investigación y enseñanza del inglés. Financia matrícula, manutención, seguro médico y pasaje aéreo. Los candidatos deben ser ciudadanos mexicanos con excelencia académica y compromiso con el liderazgo comunitario. Es una de las becas más prestigiosas para estudiantes latinoamericanos.', 'https://www.fulbright.org.mx/', '2026-10-15', ARRAY['internacional', 'posgrado', 'investigación', 'liderazgo', 'Estados Unidos'], 'posgrado', 'general'),
('Becas Antorchas', 'Fundación BBVA México', 'México', 'scholarship', true, 'Programa de becas de la Fundación BBVA que apoya a jóvenes mexicanos con alto potencial de liderazgo para cursar estudios de posgrado en el extranjero. Financia matrícula completa, manutención, seguro médico y gastos de viaje. Los postulantes deben ser mexicanos menores de 30 años con excelencia académica y compromiso social.', 'https://www.fundacionbbva.mx/', '2026-09-01', ARRAY['internacional', 'posgrado', 'liderazgo', 'fundación', 'México'], 'posgrado', 'general'),
('Becas OEA', 'Organización de Estados Americanos', 'América', 'scholarship', true, 'Programa de becas de la OEA para estudiantes de países miembros para estudios de posgrado en universidades de las Américas. Financia matrícula, manutención y otros gastos académicos. El programa busca fortalecer la cooperación educativa y el desarrollo de capital humano en la región.', 'https://www.oas.org/es/becas/', '2026-08-01', ARRAY['internacional', 'posgrado', 'OEA', 'América', 'cooperación'], 'posgrado', 'general'),
('Becas CONACYT (hoy SEP-CONAHCYT)', 'Consejo Nacional de Humanidades, Ciencias y Tecnologías', 'México', 'scholarship', true, 'Programa de becas del gobierno mexicano para estudios de maestría, doctorado y posdoctorado en instituciones nacionales e internacionales. Financia matrícula, manutención mensual y apoyo para estancias de investigación. Es el principal programa de formación de investigadores de México.', 'https://www.conahcyt.gob.mx/', '2026-06-01', ARRAY['nacional', 'posgrado', 'investigación', 'México', 'formación doctoral'], 'posgrado', 'general'),
('Becas UNAM al Extranjero', 'Universidad Nacional Autónoma de México', 'Internacional', 'scholarship', true, 'Programa de becas de la UNAM para estudiantes y egresados para realizar estudios de posgrado, estancias de investigación y movilidad académica en el extranjero. Financia matrícula, manutención, seguro médico y gastos de viaje.', 'https://www.dgire.unam.mx/', '2026-09-15', ARRAY['universidad', 'posgrado', 'movilidad', 'México', 'investigación'], 'posgrado', 'general'),
('DAAD (Alemania)', 'Servicio Académico Alemán de Intercambio', 'Alemania', 'scholarship', true, 'Becas del gobierno alemán a través del DAAD para estudios de posgrado, investigación y capacitación profesional en universidades e instituciones alemanas. Cubren manutención mensual, matrícula y seguro médico. Abierto a todas las disciplinas incluyendo ciencias de la salud.', 'https://www.daad.de/', '2026-10-15', ARRAY['Alemania', 'posgrado', 'investigación', 'gobierno', 'académico'], 'posgrado', 'general'),
('Becas Chevening', 'Gobierno del Reino Unido', 'Reino Unido', 'scholarship', true, 'Prestigiosa beca del gobierno británico para profesionales con liderazgo y potencial para cursar un máster en universidades del Reino Unido. Financia matrícula, manutención, viajes y otros gastos. Dirigida a ciudadanos de países elegibles con al menos 2 años de experiencia laboral.', 'https://www.chevening.org/', '2026-11-02', ARRAY['Reino Unido', 'máster', 'liderazgo', 'profesional', 'todos los campos'], 'posgrado', 'general'),
('Erasmus Mundus', 'Unión Europea', 'Europa', 'scholarship', true, 'Programa de la Unión Europea que ofrece becas para estudios de máster y doctorado conjuntos en universidades europeas y asociadas. Cubre matrícula, viaje, instalación y manutención. Abierto a estudiantes de cualquier país del mundo incluyendo ciencias de la salud.', 'https://erasmus-plus.ec.europa.eu/', '2026-01-15', ARRAY['movilidad europea', 'máster conjuntos', 'doctorado', 'intercambio cultural', 'UE'], 'posgrado', 'general'),
('Rhodes Scholarship', 'Rhodes Trust', 'Reino Unido', 'scholarship', true, 'El programa internacional de becas más antiguo del mundo que permite a jóvenes excepcionales realizar estudios de posgrado a tiempo completo en la Universidad de Oxford. Financia matrícula, manutención y viajes por al menos dos años. Está abierto a todas las disciplinas incluyendo ciencias de la salud.', 'https://www.rhodeshouse.ox.ac.uk/', '2026-10-01', ARRAY['Oxford', 'internacional', 'posgrado', 'líderes', 'financiamiento total'], 'posgrado', 'general'),
('Marshall Scholarship', 'Gobierno del Reino Unido', 'Reino Unido', 'scholarship', true, 'Beca prestigiosa financiada por el gobierno del Reino Unido que permite a ciudadanos estadounidenses realizar estudios de posgrado en universidades británicas por hasta tres años. Cubre matrícula, gastos de manutención, viajes y otros beneficios.', 'https://www.marshallscholarship.org/', '2026-09-23', ARRAY['Reino Unido', 'ciudadanos estadounidenses', 'posgrado', 'liderazgo', 'intercambio'], 'posgrado', 'general'),
('Australia Awards', 'Gobierno de Australia', 'Australia', 'scholarship', true, 'Becas prestigiosas del gobierno australiano dirigidas a líderes emergentes de países en desarrollo para estudios de pregrado o posgrado en instituciones australianas. Cubren matrícula, manutención, pasaje aéreo y seguro médico completo.', 'https://www.dfat.gov.au/people-to-people/australia-awards', '2026-04-30', ARRAY['internacional', 'posgrado', 'desarrollo', 'gobierno', 'liderazgo'], 'posgrado', 'general'),
('Gates Millennium Scholars', 'Fundación Bill y Melinda Gates', 'Estados Unidos', 'scholarship', true, 'Programa de becas financiado por la Fundación Gates que apoya a estudiantes de color con necesidades financieras en cualquier disciplina de pregrado. Otorga hasta 20,000 becas completas que cubren matrícula, alojamiento, libros y gastos de manutención.', 'https://www.gmsp.org/', '2026-09-15', ARRAY['pregrado', 'posgrado', 'diversidad', 'Estados Unidos', 'integral'], 'universidad', 'general'),
('Coca-Cola Scholars', 'Coca-Cola Scholars Foundation', 'Estados Unidos', 'scholarship', true, 'Programa de becas que reconoce a estudiantes de último año de secundaria en Estados Unidos que demuestran liderazgo, servicio comunitario y acción positiva. Otorga 150 becas de $20,000 cada año para estudios universitarios.', 'https://www.coca-colascholarsfoundation.org/', '2026-10-31', ARRAY['pregrado', 'liderazgo', 'servicio comunitario', 'Estados Unidos', 'preparatoria'], 'universidad', 'general'),
('Jack Kent Cooke Foundation', 'Jack Kent Cooke Foundation', 'Estados Unidos', 'scholarship', true, 'Fundación que ofrece múltiples programas de becas para estudiantes con alto rendimiento académico y necesidad financiera. El College Scholarship otorga hasta $55,000 anuales para pregrado. Las becas están abiertas a todos los campos incluyendo ciencias de la salud.', 'https://www.jkcf.org/our-scholarships/', '2026-11-01', ARRAY['pregrado', 'necesidad financiera', 'Estados Unidos', 'transferencia', 'asesoría'], 'universidad', 'general'),
('Barry Goldwater Scholarship', 'Barry Goldwater Foundation', 'Estados Unidos', 'scholarship', true, 'La beca preeminente de Estados Unidos para estudiantes universitarios de segundo y tercer año que aspiran a carreras de investigación en ciencias naturales, matemáticas e ingeniería. Otorga hasta $7,500 anuales.', 'https://goldwater.scholarsapply.org/', '2026-01-31', ARRAY['investigación', 'STEM', 'pregrado', 'ciencias', 'Estados Unidos'], 'universidad', 'ciencias'),
('Paul & Daisy Soros Fellowships', 'Paul & Daisy Soros Fellowships', 'Estados Unidos', 'scholarship', true, 'Becas meritocráticas para inmigrantes e hijos de inmigrantes que cursan estudios de posgrado en Estados Unidos. Otorga hasta $90,000 en apoyo financiero durante dos años para maestría o doctorado en cualquier campo.', 'https://www.pdsoros.org/', '2026-10-26', ARRAY['posgrado', 'inmigrantes', 'meritocrático', 'Estados Unidos', 'comunidad'], 'posgrado', 'general'),
('Hertz Foundation Fellowship', 'Hertz Foundation', 'Estados Unidos', 'scholarship', true, 'Una de las becas de doctorado más generosas de Estados Unidos, dirigida a estudiantes excepcionales en ciencias aplicadas, ingeniería y matemáticas. Otorga hasta $250,000 de financiamiento a lo largo de cinco años.', 'https://www.hertzfoundation.org/the-fellowship/', '2026-10-23', ARRAY['doctorado', 'ciencias aplicadas', 'ingeniería', 'investigación', 'prestigioso'], 'posgrado', 'ingenieria'),
('GEM Fellowship', 'National GEM Consortium', 'Estados Unidos', 'scholarship', true, 'Programa del National GEM Consortium que ofrece becas de maestría y doctorado en ciencias aplicadas e ingeniería para estudiantes de grupos subrepresentados. Incluye pasantías remuneradas con empleadores corporativos.', 'https://www.gemfellowship.org/', '2026-10-01', ARRAY['posgrado', 'STEM', 'diversidad', 'ingeniería', 'pasantía'], 'posgrado', 'ingenieria'),
('SMART Scholarship (DoD)', 'Departamento de Defensa de Estados Unidos', 'Estados Unidos', 'scholarship', true, 'Programa de becas del Departamento de Defensa que financia estudios de pregrado y posgrado en campos STEM críticos para la defensa nacional. Cubre matrícula completa, estipendio y garantiza empleo tras la graduación.', 'https://smartscholarship.org/', '2026-12-01', ARRAY['pregrado', 'posgrado', 'defensa', 'STEM', 'empleo garantizado'], 'universidad', 'general'),
('Open Society Foundations', 'Open Society Foundations', 'Internacional', 'scholarship', true, 'Las Open Society Foundations ofrecen diversas becas para estudiantes y profesionales comprometidos con la construcción de democracias inclusivas y el respeto a los derechos humanos. Cubren estudios de posgrado en derecho, ciencias políticas, salud pública y más.', 'https://www.opensocietyfoundations.org/', '2026-06-01', ARRAY['posgrado', 'derechos humanos', 'internacional', 'justicia social', 'democracia'], 'posgrado', 'general'),
('Aga Khan Foundation', 'Aga Khan Foundation', 'Internacional', 'scholarship', true, 'Programa de becas internacionales para estudiantes de países en desarrollo que demuestran necesidad financiera excepcional y alto rendimiento académico. Financia estudios de maestría y doctorado. La beca funciona como préstamo parcial, con la mitad convertida en donación.', 'https://www.akdn.org/our-agencies/aga-khan-foundation', '2026-03-31', ARRAY['posgrado', 'países en desarrollo', 'desarrollo', 'necesidad financiera', 'internacional'], 'posgrado', 'general'),
('Joint Japan/World Bank', 'Banco Mundial / Gobierno de Japón', 'Internacional', 'scholarship', true, 'Programa de becas de posgrado financiado por el Gobierno de Japón a través del Banco Mundial, dirigido a profesionales de mediana trayectoria de países en desarrollo. Financia maestrías en áreas relacionadas con desarrollo.', 'https://www.worldbank.org/en/about/careers/programs-and-internships/joint-japan-world-bank-graduate-scholarship-program', '2026-04-15', ARRAY['posgrado', 'desarrollo', 'Japón', 'banco mundial', 'profesional'], 'posgrado', 'general'),
('OPEC Fund Scholarships', 'Fondo OPEP para el Desarrollo Internacional', 'Internacional', 'scholarship', true, 'El Fondo OPEP ofrece becas de posgrado para estudiantes de países en desarrollo. Financia estudios de maestría y doctorado en campos relacionados con el desarrollo sostenible incluyendo energía, salud pública e ingeniería.', 'https://www.opecfund.org/', '2026-06-30', ARRAY['posgrado', 'desarrollo sostenible', 'OPEP', 'internacional', 'energía'], 'posgrado', 'general'),
('TU Delft Excellence', 'TU Delft', 'Países Bajos', 'scholarship', true, 'La Universidad Tecnológica de Delft ofrece múltiples becas de excelencia para estudiantes internacionales de maestría en ingeniería, ciencias aplicadas, tecnología, arquitectura y diseño.', 'https://www.tudelft.nl/en/education/financial-matters/scholarships', '2026-02-01', ARRAY['maestría', 'Países Bajos', 'ingeniería', 'excelencia', 'tecnología'], 'posgrado', 'ingenieria'),
('Holland Scholarship', 'Gobierno de los Países Bajos', 'Países Bajos', 'scholarship', true, 'Beca del gobierno holandés para estudiantes internacionales de fuera del Espacio Económico Europeo para estudios de pregrado o maestría. Otorga €5,000 como contribución a la matrícula del primer año.', 'https://www.studyinholland.nl/finances/scholarships', '2026-02-01', ARRAY['pregrado', 'maestría', 'Países Bajos', 'internacional', 'europeo'], 'universidad', 'general'),
('Pierre Elliott Trudeau Foundation', 'Fundación Pierre Elliott Trudeau', 'Canadá', 'scholarship', true, 'Una de las becas doctorales más prestigiosas de Canadá, otorgada a candidatos excepcionales al doctorado que demuestren liderazgo, compromiso cívico y excelencia académica. Otorga hasta $60,000 anuales durante cuatro años.', 'https://www.trudeaufoundation.ca/scholarships/doctors', '2026-12-01', ARRAY['doctorado', 'Canadá', 'liderazgo', 'investigación', 'interdisciplinario'], 'posgrado', 'general'),
('Chinese Government Scholarship (CSC)', 'China Scholarship Council', 'China', 'scholarship', true, 'Programa de becas del gobierno chino para estudiantes internacionales. Financia programas de maestría y doctorado en cualquier campo incluyendo ingeniería, ciencias de la salud y humanidades.', 'https://www.campuschina.org/', '2026-04-30', ARRAY['posgrado', 'China', 'internacional', 'gobierno', 'cultural'], 'posgrado', 'general'),
('Korean Government Scholarship (KGSP)', 'Gobierno de Corea del Sur', 'Corea del Sur', 'scholarship', true, 'Programa de becas del gobierno de Corea del Sur para maestría o doctorado en universidades coreanas. Otorga matrícula completa, estipendio mensual, alojamiento, pasaje aéreo y seguro médico.', 'https://www.studyinkorea.go.kr/', '2026-03-01', ARRAY['posgrado', 'Corea del Sur', 'internacional', 'gobierno', 'asiático'], 'posgrado', 'general'),
('MEXT Japanese Government', 'Ministerio de Educación de Japón', 'Japón', 'scholarship', true, 'Beca del Ministerio de Educación de Japón (MEXT) para estudios universitarios y de posgrado. Financia maestría, doctorado e investigación en cualquier campo. Cubre matrícula, estipendio, pasaje y seguro médico.', 'https://www.studyinjapan.go.jp/en/', '2026-04-18', ARRAY['posgrado', 'Japón', 'internacional', 'gobierno', 'cultura'], 'posgrado', 'general'),
('Swedish Institute Scholarships', 'Swedish Institute', 'Suecia', 'scholarship', true, 'Becas del gobierno sueco para estudiantes internacionales de países en desarrollo para máster en universidades suecas. Financia matrícula, manutención, viaje y seguro médico. Requiere liderazgo y compromiso con el desarrollo sostenible.', 'https://si.se/en/', '2026-02-15', ARRAY['desarrollo sostenible', 'liderazgo', 'igualdad de género', 'máster', 'Suecia'], 'posgrado', 'general'),
('Turkish Government Scholarships', 'Gobierno de Turquía', 'Turquía', 'scholarship', true, 'Programa integral del gobierno turco que cubre desde estudios de técnico superior hasta doctorado e investigación. Financia matrícula, alojamiento, seguro médico, curso de idioma turco, manutención y boleto aéreo.', 'https://www.turkiyeburslari.gov.tr/', '2026-02-20', ARRAY['programa integral', 'todos los niveles', 'curso de idiomas', 'Turquía', 'universidades turcas'], 'universidad', 'general'),
('Stipendium Hungaricum', 'Gobierno de Hungría', 'Hungría', 'scholarship', true, 'Programa de becas del gobierno húngaro que ofrece estudios de pregrado, máster, doctorado e investigación en universidades húngaras. Cubre matrícula, manutención mensual, alojamiento y seguro médico.', 'https://stipendiumhungaricum.hu/', '2026-01-15', ARRAY['pregrado', 'máster', 'doctorado', 'Hungría', 'centro de Europa'], 'universidad', 'general'),
('French Government Scholarships (Eiffel)', 'Gobierno de Francia', 'Francia', 'scholarship', true, 'Becas del gobierno francés administradas por Campus France para estudios de máster y doctorado. El programa Eiffel Excellence ofrece financiamiento completo. Abierto a todos los campos.', 'https://www.campusfrance.org/', '2026-01-10', ARRAY['Eiffel', 'máster', 'doctorado', 'Francia', 'grandes escuelas'], 'posgrado', 'general'),
('Swiss Government Excellence Scholarships', 'Gobierno de Suiza', 'Suiza', 'scholarship', true, 'Becas del gobierno suizo para investigadores postdoctorales y estudiantes de posgrado de todo el mundo para realizar investigación o estudios en universidades suizas.', 'https://www.sbfi.admin.ch/', '2026-12-01', ARRAY['investigación', 'postdoctorado', 'excelencia académica', 'Suiza', 'todas las disciplinas'], 'posgrado', 'general');

-- INTERNSHIPS
INSERT INTO opportunities (title, institution, location, type, funding, description, link, deadline, tags, educational_level, educational_field) VALUES
('Google Internships', 'Google', 'Estados Unidos', 'internship', true, 'Google ofrece programas de pasantías para estudiantes universitarios y de posgrado en áreas de ingeniería, negocios, ciencias de la computación y diseño. Los participantes trabajan en proyectos reales junto a ingenieros de Google.', 'https://buildyourfuture.withgoogle.com/', '2026-06-01', ARRAY['tecnología', 'ingeniería', 'pasantía remunerada', 'innovación', 'Google'], 'universidad', 'general'),
('Microsoft Internships', 'Microsoft', 'Estados Unidos', 'internship', true, 'Microsoft ofrece pasantías remuneradas para estudiantes en tecnología, ingeniería de software, negocios, marketing y diseño. Los pasantes participan en el desarrollo de productos como Azure y Office 365.', 'https://jobs.careers.microsoft.com/', '2026-06-01', ARRAY['tecnología', 'software', 'pasantía remunerada', 'diversidad', 'Microsoft'], 'universidad', 'general'),
('Apple Internships', 'Apple', 'Estados Unidos', 'internship', true, 'Apple ofrece oportunidades de pasantías para estudiantes universitarios en ingeniería de software, hardware, diseño, marketing y operaciones. Los participantes trabajan en productos emblemáticos como iPhone y Mac.', 'https://jobs.apple.com/en-us/search?location=&team=&experience=&standard=student', '2026-06-01', ARRAY['tecnología', 'diseño', 'innovación', 'hardware', 'Apple'], 'universidad', 'general'),
('Amazon Internships', 'Amazon', 'Estados Unidos', 'internship', true, 'Amazon ofrece pasantías remuneradas para estudiantes en ingeniería de software, ciencia de datos, operaciones, finanzas y gestión de producto. El programa Summer Internship dura 12 semanas.', 'https://www.amazon.jobs/', '2026-06-01', ARRAY['tecnología', 'cloud', 'pasantía remunerada', 'operaciones', 'Amazon'], 'universidad', 'general'),
('Goldman Sachs Programs', 'Goldman Sachs', 'Estados Unidos', 'internship', true, 'Goldman Sachs ofrece programas de pasantías para estudiantes interesados en finanzas, banca de inversión y tecnología financiera. El programa de verano dura 10 semanas.', 'https://www.goldmansachs.com/careers/students/', '2026-05-01', ARRAY['finanzas', 'banca', 'pasantía remunerada', 'Wall Street', 'Goldman Sachs'], 'universidad', 'general'),
('NASA Internships', 'NASA', 'Estados Unidos', 'internship', true, 'NASA ofrece pasantías pagadas a través de los programas OSTEM y Pathways para estudiantes universitarios y de posgrado. NASA acepta estudiantes de áreas STEM y no-STEM incluyendo ciencias de la salud.', 'https://intern.nasa.gov/', '2026-03-01', ARRAY['espacio', 'ciencia', 'pasantía remunerada', 'exploración', 'NASA'], 'universidad', 'general'),
('World Bank Internships', 'Banco Mundial', 'Internacional', 'internship', true, 'El Banco Mundial ofrece pasantías remuneradas para estudiantes de posgrado interesados en desarrollo internacional, economía, salud pública y políticas públicas.', 'https://www.worldbank.org/en/about/careers/internships', '2026-04-01', ARRAY['desarrollo internacional', 'políticas públicas', 'salud global', 'economía', 'Banco Mundial'], 'universidad', 'general'),
('UN Internships', 'Naciones Unidas', 'Internacional', 'internship', true, 'Las Naciones Unidas ofrecen pasantías en agencias como OMS, UNESCO, UNICEF y PNUD. Las oportunidades abarcan salud pública, derechos humanos, desarrollo sostenible y administración.', 'https://careers.un.org/', '2026-12-31', ARRAY['diplomacia', 'salud global', 'desarrollo sostenible', 'derechos humanos', 'ONU'], 'universidad', 'general'),
('European Commission Traineeships', 'Comisión Europea', 'Europa', 'internship', true, 'La Comisión Europea ofrece el programa Blue Book, un programa pagado de 5 meses para jóvenes graduados de todo el mundo. Los pasantes trabajan en políticas de la Unión Europea.', 'https://commission.europa.eu/jobs_en', '2026-01-31', ARRAY['Unión Europea', 'políticas públicas', 'pasantía pagada', 'gobierno', 'Bruselas'], 'universidad', 'general'),
('CERN Technical Student', 'CERN', 'Europa', 'internship', true, 'CERN ofrece pasantías para estudiantes técnicos y universitarios en física experimental, ingeniería, ciencias de datos, matemáticas y software.', 'https://careers.cern/', '2026-03-15', ARRAY['física', 'ingeniería', 'ciencia de datos', 'investigación', 'CERN'], 'universidad', 'general'),
('ESA Young Graduate Trainee', 'Agencia Espacial Europea', 'Europa', 'internship', true, 'La ESA ofrece el programa YGT para graduados recientes de universidades europeas. El programa dura un año en ingeniería aeroespacial, ciencias de la Tierra y exploración espacial.', 'https://www.esa.int/About_Us/Careers_at_ESA', '2026-03-15', ARRAY['espacio', 'ingeniería aeroespacial', 'investigación', 'exploración espacial', 'ESA'], 'universidad', 'general'),
('Max Planck Internships', 'Sociedad Max Planck', 'Alemania', 'internship', true, 'La Sociedad Max Planck ofrece pasantías de investigación para estudiantes internacionales en institutos de primer nivel en Alemania en ciencias naturales, ciencias de la vida y más.', 'https://internship.mpg.de/', '2026-05-01', ARRAY['investigación', 'ciencias naturales', 'Alemania', 'académico', 'Max Planck'], 'universidad', 'general'),
('ETH Zurich Internships', 'ETH Zurich', 'Suiza', 'internship', true, 'ETH Zurich ofrece pasantías de investigación en ingeniería, ciencias naturales, matemáticas, arquitectura, ciencias de la computación y ciencias de la salud.', 'https://ethz.ch/en/the-eth-zh/working-at-eth-zh/internships.html', '2026-06-01', ARRAY['investigación', 'ingeniería', 'Suiza', 'académico', 'ETH Zurich'], 'universidad', 'general'),
('TU Munich Careers', 'Universidad Técnica de Múnich', 'Alemania', 'internship', true, 'TUM, designada como Universidad de Excelencia, ofrece pasantías a través de su Career Service y oportunidades de investigación con TUM Venture Labs.', 'https://www.tum.de/en/', '2026-06-01', ARRAY['ingeniería', 'investigación', 'Alemania', 'innovación', 'TUM'], 'universidad', 'general');

-- RESEARCH OPPORTUNITIES
INSERT INTO opportunities (title, institution, location, type, funding, description, link, deadline, tags, educational_level, educational_field) VALUES
('NIH Summer Internship Program', 'Instituto Nacional de Salud (NIH)', 'Estados Unidos', 'research', true, 'Programa de pasantías del NIH para estudiantes universitarios y de posgrado. Ofrece experiencia práctica de investigación en laboratorios del NIH en disciplinas biomédicas y ciencias de la salud.', 'https://www.training.nih.gov/', '2026-03-01', ARRAY['pasantías', 'investigación biomédica', 'verano', 'Estados Unidos', 'ciencias de la salud'], 'universidad', 'general'),
('HHMI Gilliam Fellowships', 'Howard Hughes Medical Institute', 'Estados Unidos', 'research', true, 'Las Becas Gilliam están diseñadas para apoyar a estudiantes de doctorado en ciencias biomédicas y ciencias de la salud de grupos subrepresentados.', 'https://www.hmi.org/our-work/gilliam-fellowships', '2026-03-01', ARRAY['doctorado', 'diversidad en ciencia', 'ciencias biomédicas', 'liderazgo', 'mentoría'], 'posgrado', 'general'),
('EMBO Fellowships', 'Organización Europea de Biología Molecular', 'Europa', 'research', true, 'Las Becas EMBO apoyan a investigadores posdoctorales en ciencias de la vida y ciencias de la salud en instituciones europeas.', 'https://www.embo.org/', '2026-01-15', ARRAY['investigación posdoctoral', 'ciencias de la vida', 'Europa', 'colaboración internacional', 'biología molecular'], 'posgrado', 'general'),
('NSF Graduate Research Fellowship', 'National Science Foundation', 'Estados Unidos', 'research', true, 'El NSF GRFP apoya a estudiantes destacados en maestría o doctorado en campos STEM. Otorga beca de cinco años con estipendio de $37,000 anuales.', 'https://www.nsfgrfp.org/', '2026-10-20', ARRAY['doctorado', 'STEM', 'Estados Unidos', 'estipendio', 'ciencias de la salud'], 'posgrado', 'general'),
('ERC Grants', 'Consejo Europeo de Investigación', 'Europa', 'research', true, 'Los Grants del ERC son los prestigiosos premios de investigación del Horizonte Europa para investigación de frontera en cualquier campo. Fondos desde 1.5 hasta 3.5 millones de euros.', 'https://erc.europa.eu/', '2026-04-15', ARRAY['investigación de frontera', 'Europa', 'prestigioso', 'todas las disciplinas', 'innovación'], 'profesional', 'general'),
('Marie Skłodowska-Curie Actions', 'Horizonte Europa', 'Europa', 'research', true, 'Las MSCA financian la excelencia en investigación y formación a nivel mundial. Ofrecen becas para investigadores postdoctorales, redes de formación doctoral y programas de intercambio.', 'https://mariecurie-actions.eu/', '2026-09-16', ARRAY['movilidad internacional', 'formación doctoral', 'posdoctoral', 'Horizonte Europa', 'interdisciplinariedad'], 'posgrado', 'general'),
('DAAD Research Grants', 'Servicio Académico Alemán', 'Alemania', 'research', true, 'El DAAD ofrece numerosas becas de investigación para académicos e investigadores internacionales en Alemania. Abierto a todas las disciplinas.', 'https://www.daad.de/en/', '2026-10-15', ARRAY['Alemania', 'intercambio académico', 'investigación', 'todas las disciplinas', 'financiamiento internacional'], 'posgrado', 'general'),
('Cancer Research UK', 'Cancer Research UK', 'Reino Unido', 'research', true, 'Cancer Research UK es la principal organización benéfica de investigación del cáncer del mundo, financiando más de 4,000 científicos.', 'https://www.cancerresearchuk.org/', '2026-12-01', ARRAY['cáncer', 'investigación oncológica', 'Reino Unido', 'salud', 'benéfica científica'], 'profesional', 'ciencias_salud'),
('Wellcome Trust Fellowships', 'Wellcome Trust', 'Reino Unido', 'research', true, 'Las Becas Wellcome financian investigación de vanguardia para mejorar la vida, la salud y el bienestar. Cubre ciencias biomédicas, salud, ciencias físicas e ingeniería.', 'https://wellcome.org/grant-funding/', '2026-12-01', ARRAY['financiamiento de investigación', 'salud global', 'múltiples disciplinas', 'carrera investigadora', 'Reino Unido'], 'profesional', 'general');

-- HEALTH SCIENCES OPPORTUNITIES
INSERT INTO opportunities (title, institution, location, type, funding, description, link, deadline, tags, educational_level, educational_field) VALUES
('Fogarty International Fellowship', 'NIH Fogarty International Center', 'Estados Unidos', 'research', true, 'El Fogarty International Center ofrece becas para investigadores y profesionales de salud que deseen desarrollar capacidades de investigación en salud global.', 'https://www.fic.nih.gov/', '2026-01-15', ARRAY['salud global', 'investigación biomédica', 'enfermedades infecciosas', 'becas internacionales', 'NIH'], 'posgrado', 'ciencias_salud'),
('CDC Epidemic Intelligence Service', 'Centros para el Control y la Prevención de Enfermedades', 'Estados Unidos', 'research', true, 'El EIS del CDC es un programa de becas de dos años que forma a profesionales de salud pública en investigación de brotes epidémicos y vigilancia epidemiológica.', 'https://www.cdc.gov/eis/', '2026-06-19', ARRAY['epidemiología', 'salud pública', 'investigación de campo', 'emergencias sanitarias', 'vigilancia epidemiológica'], 'posgrado', 'ciencias_salud'),
('MSF (Doctors Without Borders)', 'Médicos Sin Fronteras', 'Internacional', 'internship', false, 'Médicos Sin Fronteras es una organización médica humanitaria que brinda asistencia a víctimas de conflictos, desastres y epidemias en más de 70 países.', 'https://www.msf.org/', '2026-12-31', ARRAY['humanitaria', 'medicina de emergencia', 'conflictos armados', 'voluntariado internacional', 'crisis humanitarias'], 'profesional', 'ciencias_salud'),
('Global Health Corps', 'Global Health Corps', 'Internacional', 'scholarship', true, 'GHC ofrece el programa Africa Leadership Accelerator, una beca de liderazgo para profesionales jóvenes de salud pública de Malawi, Ruanda, Uganda y Zambia.', 'https://globalhealthcorps.org/', '2026-02-01', ARRAY['liderazgo sanitario', 'África', 'salud pública comunitaria', 'capacitación profesional', 'desarrollo de liderazgo'], 'profesional', 'ciencias_salud'),
('Partners in Health', 'Partners In Health', 'Internacional', 'internship', false, 'PIH es una organización global de salud y justicia social que brinda atención médica de alta calidad a comunidades empobrecidas en más de 15 países.', 'https://www.pih.org/', '2026-12-31', ARRAY['justicia social', 'sistemas de salud', 'equidad sanitaria', 'atención primaria', 'salud comunitaria'], 'profesional', 'ciencias_salud'),
('Clinton Health Access Initiative', 'CHAI', 'Internacional', 'internship', false, 'CHAI trabaja en la intersección de gobierno, empresa y salud para catalizar un acceso más equitativo a la atención sanitaria en más de 35 países.', 'https://www.clintonhealthaccess.org/', '2026-12-31', ARRAY['acceso a salud', 'VIH/SIDA', 'malaria', 'sistemas de salud', 'equidad sanitaria global'], 'profesional', 'ciencias_salud'),
('Harvard T.H. Chan School of Public Health', 'Harvard University', 'Estados Unidos', 'research', true, 'Una de las escuelas de salud pública más prestigiosas del mundo, ofreciendo MPH, SM, MS, PhD y DrPH en epidemiología, biostadística, nutrición y salud ambiental.', 'https://www.hsph.harvard.edu/', '2026-12-01', ARRAY['salud pública', 'investigación sanitaria', 'epidemiología', 'política de salud', 'Harvard'], 'posgrado', 'ciencias_salud'),
('Johns Hopkins Bloomberg School', 'Johns Hopkins University', 'Estados Unidos', 'research', true, 'La escuela de salud pública más antigua y reconocida del mundo. El Bloomberg Fellows Program ofrece becas de matrícula completa para MPH o DrPH.', 'https://publichealth.jhu.edu/', '2026-12-01', ARRAY['salud pública', 'becas de matrícula completa', 'investigación epidemiológica', 'salud internacional', 'Johns Hopkins'], 'posgrado', 'ciencias_salud'),
('London School of Hygiene & Tropical Medicine', 'LSHTM', 'Reino Unido', 'research', true, 'Una de las universidades líderes mundiales en salud pública, clasificada #3 a nivel mundial. Ofrece Maestría, Doctorado y cursos cortos en epidemiología y salud tropical.', 'https://www.lshtm.ac.uk/', '2026-03-01', ARRAY['salud pública tropical', 'epidemiología', 'enfermedades infecciosas', 'investigación global', 'educación en salud'], 'posgrado', 'ciencias_salud'),
('Karolinska Institutet', 'Karolinska Institutet', 'Suecia', 'research', true, 'Una de las universidades médicas más importantes del mundo. Ofrece Maestría y Doctorado en medicina, biomedicina y salud pública. Conocida por el Premio Nobel.', 'https://ki.se/en', '2026-01-15', ARRAY['medicina', 'investigación biomédica', 'Suecia', 'premio Nobel', 'educación médica'], 'posgrado', 'ciencias_salud'),
('Duke-NUS Medical School', 'Duke-NUS Medical School', 'Singapur', 'research', true, 'Escuela de medicina de investigación en Singapur. Ofrece MD, PhD y MD-PhD. Los estudiantes de PhD reciben beca que cubre el 100% de la matrícula.', 'https://www.duke-nus.edu.sg/', '2026-01-31', ARRAY['medicina', 'investigación biomédica', 'Singapur', 'becas de mérito', 'formación médica'], 'posgrado', 'ciencias_salud');

-- PROFESSIONAL OPPORTUNITIES
INSERT INTO opportunities (title, institution, location, type, funding, description, link, deadline, tags, educational_level, educational_field) VALUES
('UNDP', 'Programa de las Naciones Unidas para el Desarrollo', 'Internacional', 'internship', false, 'UNDP ofrece pasantías, voluntariados y oportunidades profesionales. Trabaja en 170 países enfocándose en erradicar la pobreza, cambio climático y los ODS.', 'https://www.undp.org/', '2026-12-31', ARRAY['desarrollo sostenible', 'ODS', 'erradicación de pobreza', 'cooperación internacional', 'gobernanza'], 'posgrado', 'general'),
('UNESCO', 'Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura', 'Internacional', 'internship', false, 'UNESCO ofrece becas, pasantías y oportunidades en educación, ciencia, cultura y comunicación. Se requiere dominio de al menos dos idiomas oficiales de la ONU.', 'https://www.unesco.org/', '2026-12-31', ARRAY['educación', 'ciencia y cultura', 'patrimonio', 'cooperación internacional', 'inclusión social'], 'posgrado', 'general'),
('WHO', 'Organización Mundial de la Salud', 'Internacional', 'internship', false, 'La OMS ofrece pasantías, becas y oportunidades profesionales. Coordina la respuesta global a emergencias sanitarias y promueve la cobertura sanitaria universal.', 'https://www.who.int/', '2026-12-31', ARRAY['salud global', 'emergencias sanitarias', 'cobertura universal', 'epidemiología', 'normas internacionales'], 'posgrado', 'general'),
('FAO', 'Organización de las Naciones Unidas para la Alimentación y la Agricultura', 'Internacional', 'internship', false, 'FAO ofrece pasantías y oportunidades para erradicar el hambre, mejorar la agricultura sostenible y fortalecer la seguridad alimentaria mundial.', 'https://www.fao.org/', '2026-12-31', ARRAY['seguridad alimentaria', 'agricultura sostenible', 'nutrición', 'cambio climático', 'desarrollo rural'], 'posgrado', 'general'),
('IMF', 'Fondo Monetario Internacional', 'Internacional', 'internship', false, 'El FMI ofrece pasantías y oportunidades profesionales. Promueve la estabilidad financiera internacional y el crecimiento económico sostenible.', 'https://www.imf.org/', '2026-12-31', ARRAY['economía internacional', 'estabilidad financiera', 'política monetaria', 'finanzas públicas', 'cooperación económica'], 'posgrado', 'general'),
('World Bank', 'Banco Mundial', 'Internacional', 'internship', false, 'El Banco Mundial ofrece pasantías y oportunidades profesionales. Financia proyectos de desarrollo en países en vías de desarrollo.', 'https://www.worldbank.org/', '2026-12-31', ARRAY['desarrollo internacional', 'financiamiento', 'reducción de pobreza', 'infraestructura', 'empleo'], 'posgrado', 'general'),
('IDB', 'Banco Interamericano de Desarrollo', 'Internacional', 'internship', false, 'El BID ofrece pasantías y oportunidades para profesionales. Financia proyectos de desarrollo en América Latina y el Caribe.', 'https://www.iadb.org/', '2026-12-31', ARRAY['desarrollo latinoamericano', 'América Latina', 'pobreza', 'políticas públicas', 'infraestructura'], 'posgrado', 'general'),
('European Space Agency', 'Agencia Espacial Europea', 'Europa', 'internship', false, 'ESA ofrece el Junior Professional Programme y pasantías. Desarrolla misiones espaciales de exploración, observación terrestre y seguridad espacial.', 'https://www.esa.int/', '2026-03-15', ARRAY['exploración espacial', 'tecnología aeroespacial', 'ciencia', 'innovación', 'ingeniería avanzada'], 'posgrado', 'general'),
('NATO', 'Organización del Tratado del Atlántico Norte', 'Internacional', 'internship', false, 'NATO ofrece el Young Professionals Programme y pasantías. Promueve la defensa colectiva, la seguridad cooperativa y la investigación científica para la paz.', 'https://www.nato.int/', '2026-03-01', ARRAY['seguridad internacional', 'defensa colectiva', 'ciberseguridad', 'cooperación militar', 'política de seguridad'], 'posgrado', 'general'),
('Peace Corps', 'Gobierno de Estados Unidos', 'Internacional', 'internship', false, 'Programa de servicio voluntario que envía a ciudadanos americanos a trabajar en comunidades de más de 60 países durante dos años.', 'https://www.peacecorps.gov/', '2026-09-30', ARRAY['voluntariado', 'internacional', 'desarrollo comunitario', 'servicio público', 'cooperación'], 'profesional', 'general'),
('Teach For All', 'Teach For All (Red Global)', 'Internacional', 'internship', false, 'Red global de organizaciones en 63 países dedicadas a garantizar educación de calidad. Los participantes imparten en escuelas de comunidades desfavorecidas.', 'https://teachforall.org/', '2026-12-31', ARRAY['educación', 'liderazgo', 'equidad educativa', 'internacional', 'enseñanza'], 'profesional', 'educacion');

-- TECHNOLOGY OPPORTUNITIES
INSERT INTO opportunities (title, institution, location, type, funding, description, link, deadline, tags, educational_level, educational_field) VALUES
('Google Summer of Code', 'Google', 'Internacional', 'internship', true, 'Programa global enfocado en incorporar nuevos colaboradores al desarrollo de software de código abierto. Los participantes trabajan con organizaciones de código abierto por 12+ semanas.', 'https://summerofcode.withgoogle.com/', '2026-04-01', ARRAY['código abierto', 'programación', 'mentoreo', 'beca', 'desarrollo de software'], 'universidad', 'tecnologia'),
('MLH Fellowship', 'Major League Hacking', 'Internacional', 'internship', true, 'Pasantía de 12 semanas completamente remota donde los participantes aprenden ingeniería de software en proyectos de código abierto. Los fellows reciben un estipendio.', 'https://fellowship.mlh.io/', '2026-06-01', ARRAY['ingeniería de software', 'código abierto', 'pasantía remota', 'estipendio', 'open source'], 'universidad', 'tecnologia'),
('AWS Educate', 'Amazon Web Services', 'Internacional', 'course', true, 'Programa gratuito de AWS que ofrece formación en computación en la nube. Los participantes desde 13 años pueden acceder a laboratorios prácticos gratuitos.', 'https://aws.amazon.com/education/awseducate/', '2026-12-31', ARRAY['computación en la nube', 'AWS', 'gratuito', 'laboratorios prácticos', 'empleabilidad'], 'universidad', 'tecnologia'),
('Microsoft Learn Student Ambassadors', 'Microsoft', 'Internacional', 'course', true, 'Programa global para estudiantes que deseen desarrollar habilidades en inteligencia artificial y tecnología. Los embajadores construyen proyectos y organizan eventos.', 'https://studentambassadors.microsoft.com/', '2026-12-31', ARRAY['inteligencia artificial', 'Microsoft', 'liderazgo', 'acceso abierto', 'comunidad global'], 'universidad', 'general'),
('NVIDIA Deep Learning Institute', 'NVIDIA', 'Internacional', 'course', true, 'Cursos y certificaciones en inteligencia artificial, aprendizaje profundo, ciencia de datos y computación acelerada por GPU. Muchos cursos son gratuitos.', 'https://www.nvidia.com/en-us/training/', '2026-12-31', ARRAY['inteligencia artificial', 'deep learning', 'GPU', 'certificación', 'machine learning'], 'universidad', 'tecnologia'),
('IBM SkillsBuild', 'IBM', 'Internacional', 'course', true, 'Plataforma de aprendizaje gratuita con cursos de IA, ciberseguridad, ciencia de datos y computación en la nube, disponibles en más de 20 idiomas.', 'https://skillsbuild.org/', '2026-12-31', ARRAY['gratuito', 'multiidioma', 'ciberseguridad', 'ciencia de datos', 'habilidades digitales'], 'universidad', 'general'),
('Cisco Networking Academy', 'Cisco', 'Internacional', 'course', true, 'Cursos gratuitos en redes, ciberseguridad, programación Python, análisis de datos e inteligencia artificial. Incluye preparación para certificaciones Cisco.', 'https://www.netacad.com/', '2026-12-31', ARRAY['redes', 'ciberseguridad', 'certificación Cisco', 'Python', 'gratuito'], 'universidad', 'tecnologia'),
('Google IT Support Certificate', 'Google / Coursera', 'Internacional', 'course', true, 'Certificado profesional de Google para empleabilidad en soporte de TI en 3 a 6 meses. El 75% de los graduados reportan resultado laboral positivo.', 'https://www.coursera.org/professional-certificates/google-it-support', '2026-12-31', ARRAY['soporte de TI', 'certificación profesional', 'Google', 'ciberseguridad', 'redes'], 'universidad', 'general'),
('Oracle Academy', 'Oracle', 'Internacional', 'course', true, 'Programa educativo gratuito de Oracle con currícula, software y entornos de práctica en la nube. Cubre Java, bases de datos y cloud computing.', 'https://academy.oracle.com/', '2026-12-31', ARRAY['Oracle', 'Java', 'bases de datos', 'cloud', 'gratuito'], 'universidad', 'tecnologia'),
('SAP Next-Gen', 'SAP', 'Internacional', 'course', true, 'Programa estudiantil con talleres, hackathons y eventos sobre tecnologías SAP. Incluye el Young Professionals Program de 2 meses con certificaciones.', 'https://www.sap.com/next-gen.html', '2026-12-31', ARRAY['ERP', 'SAP', 'empresa inteligente', 'hackathons', 'certificación'], 'universidad', 'general');
